"use strict";
const express=require("express"),jwt=require("jsonwebtoken");
const stripe=require("stripe")(process.env.STRIPE_SECRET_KEY);
const Tenant=require("../models/Tenant");
const TenantSubscription=require("../models/TenantSubscription");
const Payment=require("../models/TenantSubscriptionPayment");
const router=express.Router(),SECRET=process.env.JWT_SECRET||"dev_secret";
const BASE=String(process.env.PUBLIC_BASE_URL||"https://sunbeam-933q.onrender.com").replace(/\/+$/,"");
const clean=v=>String(v??"").trim();
function auth(req,res,next){const h=clean(req.headers.authorization);if(!h.toLowerCase().startsWith("bearer "))return res.status(401).json({message:"Access Denied"});try{const d=jwt.verify(h.slice(7).trim(),SECRET),r=clean(d.role).toUpperCase().replace(/[\s-]+/g,"_");if(!["SUPER_ADMIN","SUPERADMIN","ADMIN"].includes(r)||!d.tenantId)return res.status(403).json({message:"Admin access required"});req.authUser={tenantId:String(d.tenantId),role:r};next()}catch(e){return res.status(401).json({message:"Invalid Token"})}}
function addCycle(d,c){const n=new Date(d);c==="MONTHLY"?n.setUTCMonth(n.getUTCMonth()+1):n.setUTCFullYear(n.getUTCFullYear()+1);return n}
async function ensure(id){return await TenantSubscription.findOne({tenantId:id})||await TenantSubscription.create({tenantId:id,planName:"GH Mobility",billingCycle:"ANNUAL",amount:0,status:"ACTIVE",graceDays:3,locked:false})}
function state(s){const now=new Date();if(s.status==="TRIAL"&&s.trialEndsAt&&new Date(s.trialEndsAt)>now)return{status:"TRIAL",locked:false};if(!s.dueDate)return{status:"ACTIVE",locked:false};const due=new Date(s.dueDate);if(now<=due)return{status:"ACTIVE",locked:false};const g=new Date(due);g.setUTCDate(g.getUTCDate()+Number(s.graceDays||0));return now<=g?{status:"PAST_DUE",locked:false}:{status:"SUSPENDED",locked:true}}
async function paid(s,p,session){if(p.status==="PAID")return;const pi=typeof session.payment_intent==="string"?await stripe.paymentIntents.retrieve(session.payment_intent):session.payment_intent;if(!pi||pi.status!=="succeeded")return;let method=(pi.payment_method_types&&pi.payment_method_types[0])||"";p.status="PAID";p.paymentIntentId=pi.id;p.paymentMethod=method==="us_bank_account"?"ACH":method==="card"?"CARD":method.toUpperCase();p.paidAt=new Date();await p.save();s.lastPaymentDate=p.paidAt;s.currentPeriodStart=p.paidAt;s.dueDate=addCycle(p.paidAt,s.billingCycle);s.nextBillingDate=s.dueDate;s.status="ACTIVE";s.locked=false;await s.save();await Tenant.findByIdAndUpdate(s.tenantId,{$set:{enabled:true,subscriptionStatus:"ACTIVE"}})}
async function reconcile(s){const list=await Payment.find({tenantId:s.tenantId,status:{$in:["PENDING","PROCESSING"]},checkoutSessionId:{$ne:""}}).sort({createdAt:-1}).limit(5);for(const p of list){try{const session=await stripe.checkout.sessions.retrieve(p.checkoutSessionId,{expand:["payment_intent"]});const pi=session.payment_intent;if(pi&&typeof pi==="object"&&pi.status==="succeeded")await paid(s,p,session);else if(pi&&typeof pi==="object"&&["processing","requires_action"].includes(pi.status)){p.status="PROCESSING";await p.save()}}catch(e){console.log("SUBSCRIPTION RECONCILE:",e.message)}}}
router.get("/me",auth,async(req,res)=>{try{const t=await Tenant.findById(req.authUser.tenantId).lean();if(!t)return res.status(404).json({message:"Tenant not found"});let s=await ensure(t._id);await reconcile(s);s=await TenantSubscription.findOne({tenantId:t._id});const st=state(s);s.status=st.status;s.locked=st.locked;await s.save();const history=await Payment.find({tenantId:t._id}).sort({createdAt:-1}).limit(50).lean();res.json({success:true,tenant:{id:t._id,name:t.name||t.branding?.companyName||"Company"},subscription:{planName:s.planName,billingCycle:s.billingCycle,amountDue:Number(s.amount||0),status:s.status,graceDays:s.graceDays,dueDate:s.dueDate,nextBillingDate:s.nextBillingDate||s.dueDate,lastPaymentDate:s.lastPaymentDate,locked:s.locked},history})}catch(e){console.error(e);res.status(500).json({message:"Unable to load subscription"})}});
router.post("/checkout-session",auth,async(req,res)=>{try{const t=await Tenant.findById(req.authUser.tenantId);if(!t)return res.status(404).json({message:"Tenant not found"});const s=await ensure(t._id),amount=Number(s.amount||0);if(amount<=0)return res.status(400).json({message:"No subscription payment is due"});if(!s.stripeCustomerId){const c=await stripe.customers.create({name:t.name||"GH Mobility Customer",metadata:{tenantId:String(t._id)}});s.stripeCustomerId=c.id;await s.save()}const invoice="GH-"+Date.now().toString(36).toUpperCase()+"-"+String(t._id).slice(-5).toUpperCase();const p=await Payment.create({tenantId:t._id,invoiceNumber:invoice,amount,currency:s.currency||"usd",billingCycle:s.billingCycle,status:"PENDING"});const session=await stripe.checkout.sessions.create({mode:"payment",customer:s.stripeCustomerId,payment_method_types:["card","us_bank_account"],line_items:[{price_data:{currency:s.currency||"usd",product_data:{name:`${s.planName} ${s.billingCycle} Subscription`},unit_amount:Math.round(amount*100)},quantity:1}],metadata:{purpose:"GH_MOBILITY_TENANT_SUBSCRIPTION",tenantId:String(t._id),subscriptionPaymentId:String(p._id),invoiceNumber:invoice},payment_intent_data:{metadata:{purpose:"GH_MOBILITY_TENANT_SUBSCRIPTION",tenantId:String(t._id),subscriptionPaymentId:String(p._id),invoiceNumber:invoice}},success_url:`${BASE}/admin/payment.html?session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${BASE}/admin/payment.html?cancelled=1`});p.checkoutSessionId=session.id;await p.save();res.json({success:true,url:session.url})}catch(e){console.error(e);res.status(500).json({message:"Unable to start subscription payment"})}});
router.get("/verify",auth,async(req,res)=>{try{const sid=clean(req.query.session_id);if(!sid)return res.status(400).json({message:"Session required"});const p=await Payment.findOne({tenantId:req.authUser.tenantId,checkoutSessionId:sid});if(!p)return res.status(404).json({message:"Payment not found"});const s=await ensure(req.authUser.tenantId);const session=await stripe.checkout.sessions.retrieve(sid,{expand:["payment_intent"]});const pi=session.payment_intent;if(pi&&typeof pi==="object"&&pi.status==="succeeded"){await paid(s,p,session);return res.json({paid:true,processing:false})}if(pi&&typeof pi==="object"&&["processing","requires_action"].includes(pi.status)){p.status="PROCESSING";await p.save();return res.json({paid:false,processing:true})}res.json({paid:false,processing:false})}catch(e){console.error(e);res.status(500).json({message:"Unable to verify payment"})}});
module.exports=router;