"use strict";
const express=require("express"),jwt=require("jsonwebtoken"),mongoose=require("mongoose");
const SmartFormPricing=require("../models/SmartFormPricing"),SmartFormTemplate=require("../models/SmartFormTemplate"),Service=require("../models/Service");
const {calculateSmartFormPrice}=require("../services/smartFormPricingEngine");
const router=express.Router(),SECRET=process.env.JWT_SECRET||"dev_secret"; const clean=v=>String(v??"").trim(); const upper=v=>clean(v).toUpperCase();
function auth(req,res,next){try{const h=clean(req.headers.authorization);if(!h.toLowerCase().startsWith("bearer "))return res.status(401).json({success:false,message:"Access Denied"});const d=jwt.verify(h.slice(7),SECRET);req.user=d;if(!["SUPER_ADMIN","ADMIN","PLATFORM_ADMIN"].includes(upper(d.role)))return res.status(403).json({success:false,message:"Not allowed"});next();}catch(e){res.status(401).json({success:false,message:"Invalid Token"});}}
function tenant(req){return upper(req.user?.role)==="PLATFORM_ADMIN"?clean(req.query.tenantId||req.body.tenantId):clean(req.user?.tenantId);}
router.use(auth);
router.get("/templates",async(req,res)=>{try{const tid=tenant(req);const templates=await SmartFormTemplate.find({tenantId:tid,active:true}).select("name organizationId").sort({name:1}).lean();res.json({success:true,templates});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.get("/templates/:templateId",async(req,res)=>{try{const tid=tenant(req);const template=await SmartFormTemplate.findOne({_id:req.params.templateId,tenantId:tid,active:true}).lean();if(!template)return res.status(404).json({success:false,message:"Template not found"});const enabled=await Service.find({tenantId:tid,enabled:true}).select("serviceKey title pricingMode shared").sort({title:1}).lean();const saved=await SmartFormPricing.findOne({tenantId:tid,templateId:template._id}).lean();const byKey=new Map((saved?.services||[]).map(x=>[upper(x.serviceKey),x]));const services=enabled.map(s=>({...byKey.get(upper(s.serviceKey)),serviceKey:upper(s.serviceKey),serviceName:s.title||s.serviceKey,enabled:byKey.has(upper(s.serviceKey))?byKey.get(upper(s.serviceKey)).enabled!==false:true,pricingMode:byKey.get(upper(s.serviceKey))?.pricingMode||s.pricingMode||"MILE",shared:byKey.get(upper(s.serviceKey))?.shared===true||s.shared===true}));res.json({success:true,template:{_id:template._id,name:template.name},active:saved?.active!==false,services});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.put("/templates/:templateId",async(req,res)=>{try{const tid=tenant(req);const template=await SmartFormTemplate.findOne({_id:req.params.templateId,tenantId:tid,active:true}).lean();if(!template)return res.status(404).json({success:false,message:"Template not found"});const enabled=await Service.find({tenantId:tid,enabled:true}).select("serviceKey title").lean();const allowed=new Set(enabled.map(s=>upper(s.serviceKey)));const services=(Array.isArray(req.body.services)?req.body.services:[]).filter(s=>allowed.has(upper(s.serviceKey))).map(s=>({...s,serviceKey:upper(s.serviceKey)}));const pricing=await SmartFormPricing.findOneAndUpdate({tenantId:tid,templateId:template._id},{$set:{templateName:template.name,active:req.body.active!==false,services,updatedBy:req.user?.name||req.user?.username||""}},{new:true,upsert:true,setDefaultsOnInsert:true});res.json({success:true,pricing});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.post("/calculate",async(req,res)=>{try{const result=await calculateSmartFormPrice({...req.body,tenantId:tenant(req)});res.json(result);}catch(e){res.status(e.statusCode||500).json({success:false,message:e.message});}});
module.exports=router;
