const express=require("express");
const jwt=require("jsonwebtoken");
const multer=require("multer");
const mongoose=require("mongoose");
const Tenant=require("../models/Tenant");
const Trip=require("../models/Trip");
const Service=require("../models/Service");
const SmartFormTemplate=require("../models/SmartFormTemplate");
const SmartFormDocument=require("../models/SmartFormDocument");
const SmartFormCounter=require("../models/SmartFormCounter");
const analyzer=require("../services/smartFormAnalyzerService");
const builder=require("../services/smartFormBuilderService");
const router=express.Router(); const JWT_SECRET=process.env.JWT_SECRET||"dev_secret";
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024,files:1}});
const clean=v=>String(v??"").trim(); const upper=v=>clean(v).toUpperCase();
function bearer(req){const h=clean(req.headers.authorization);return h.toLowerCase().startsWith("bearer ")?h.slice(7).trim():"";}
function auth(req,res,next){try{const v=jwt.verify(bearer(req),JWT_SECRET);req.authUser={id:v.id||null,name:v.name||v.username||"",role:v.role||"",tenantId:v.tenantId||null};if(req.authUser.role!=="PLATFORM_ADMIN"&&!req.authUser.tenantId)return res.status(403).json({success:false,message:"Tenant Required"});next();}catch(_){return res.status(401).json({success:false,message:"Invalid Token"});}}
function tenantId(req){return req.authUser.role==="PLATFORM_ADMIN"?clean(req.query.tenantId||req.body?.tenantId):clean(req.authUser.tenantId);}
async function gate(req,res,next){try{const id=tenantId(req);if(!mongoose.isValidObjectId(id))return res.status(403).json({success:false,message:"Tenant Required"});const t=await Tenant.findById(id);if(!t)return res.status(404).json({success:false,message:"Tenant not found"});if(t.smartFormsEnabled!==true)return res.status(403).json({success:false,message:"Smart Forms is disabled for this company"});req.smartTenant=t;next();}catch(e){next(e);}}
function orgCode(name){const s=upper(name).replace(/[^A-Z0-9]/g,"");return (s+"XX").slice(0,2);}
function serviceCode(s){const c=upper(s?.serviceSuffix||s?.tripNumberSuffix||s?.serviceCode||s?.serviceKey);if(c)return (c+"XX").slice(0,2);const n=upper(s?.serviceName||s?.name||s?.title).replace(/[^A-Z0-9]/g,"");return (n+"XX").slice(0,2);}
async function nextCounter(tenant,kind){const field=kind==="sheet"?"nextSheetSequence":"nextTripSequence";const start=kind==="sheet"?1:100;const doc=await SmartFormCounter.findOneAndUpdate({tenantId:tenant},{$setOnInsert:{tenantId:tenant,[field]:start},$inc:{[field]:1}},{new:true,upsert:true,setDefaultsOnInsert:true});return Number(doc[field])-1;}
function slotFromField(f){const text=`${f.sectionId||""} ${f.sectionLabel||""}`;const m=text.match(/(?:trip\s*|^|\D)([1-9]\d*)\s*(?:st|nd|rd|th)?/i);return m?Number(m[1]):null;}
function requiredTripValues(v){return {pickup:clean(v.pickup),dropoff:clean(v.dropoff),tripDate:clean(v.tripDate),tripTime:clean(v.tripTime)};}
async function findEnabledService(tenant,key){const k=upper(key);return Service.findOne({tenantId:tenant,companyEnabled:true,$or:[{serviceKey:k},{serviceCode:k},{serviceSuffix:k},{tripNumberSuffix:k},{serviceIdentity:k}]});}
router.use(auth);
router.get("/feature",async(req,res)=>{try{const t=await Tenant.findById(tenantId(req)).select("smartFormsEnabled").lean();res.json({success:true,enabled:t?.smartFormsEnabled===true});}catch(_){res.status(500).json({success:false,enabled:false});}});
router.use(gate);
router.get("/services",async(req,res)=>{try{const services=await Service.find({tenantId:req.smartTenant._id,companyEnabled:true}).sort({createdAt:1}).lean();res.json({success:true,services:services.map(s=>({key:upper(s.serviceKey||s.serviceCode||s.serviceIdentity),name:clean(s.serviceName||s.serviceTitle||s.name||s.title||s.serviceKey),code:serviceCode(s)})).filter(s=>s.key&&s.name)});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.get("/clients/lookup",async(req,res)=>{try{const q=clean(req.query.q);if(q.length<2)return res.json({success:true,clients:[]});const rx=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i");const trips=await Trip.find({tenantId:req.smartTenant._id,$or:[{memberId:rx},{clientName:rx}]}).select("memberId clientName clientPhone").sort({createdAt:-1}).limit(30).lean();const seen=new Set(),clients=[];for(const t of trips){const key=clean(t.memberId)||`${clean(t.clientName)}|${clean(t.clientPhone)}`;if(!key||seen.has(key))continue;seen.add(key);clients.push({memberId:clean(t.memberId),clientName:clean(t.clientName),clientPhone:clean(t.clientPhone)});if(clients.length>=10)break;}res.json({success:true,clients});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.get("/templates",async(req,res)=>{const q={tenantId:req.smartTenant._id,archived:{$ne:true}};if(req.query.organizationId)q.organizationId=clean(req.query.organizationId);const templates=await SmartFormTemplate.find(q).select("-sourceFile.data").sort({organizationName:1,updatedAt:-1}).lean();res.json({success:true,templates});});
router.get("/templates/:id/source",async(req,res)=>{const t=await SmartFormTemplate.findOne({_id:req.params.id,tenantId:req.smartTenant._id});if(!t||!t.sourceFile?.data)return res.status(404).end();res.type(t.sourceFile.mimeType||"application/octet-stream").send(t.sourceFile.data);});
router.post("/templates/analyze",upload.single("file"),async(req,res)=>{try{if(!req.file)return res.status(400).json({success:false,message:"Blank form file is required"});const organizationId=clean(req.body.organizationId);const organizationName=clean(req.body.organizationName);if(!organizationId||!organizationName)return res.status(400).json({success:false,message:"Organization is required"});const analysis=await analyzer.analyzeBlankForm(req.file);const doc=await SmartFormTemplate.create({tenantId:req.smartTenant._id,organizationId,organizationName,organizationType:upper(req.body.organizationType||"INSURANCE"),name:clean(req.body.name||organizationName),sourceFile:{originalName:req.file.originalname,mimeType:req.file.mimetype,size:req.file.size,data:req.file.buffer},pageCount:analysis.pageCount,sections:analysis.sections,fields:analysis.fields,analysisProvider:analysis.analysisProvider,analyzedAt:new Date(),createdBy:req.authUser.name,updatedBy:req.authUser.name});const out=doc.toObject();delete out.sourceFile.data;res.status(201).json({success:true,template:out});}catch(err){console.error("SMART FORM ANALYZE ERROR",err);res.status(err?.code===11000?409:500).json({success:false,message:err?.code===11000?"A form with this name already exists for this organization":err.message});}});
router.put("/templates/:id",async(req,res)=>{try{const t=await SmartFormTemplate.findOne({_id:req.params.id,tenantId:req.smartTenant._id,organizationId:clean(req.body.organizationId)});if(!t)return res.status(404).json({success:false,message:"Template not found"});for(const k of ["name","organizationName","organizationType","active"]){if(req.body[k]!==undefined)t[k]=req.body[k];}if(Array.isArray(req.body.fields))t.fields=req.body.fields;if(Array.isArray(req.body.sections))t.sections=req.body.sections;t.updatedBy=req.authUser.name;await t.save();const out=t.toObject();delete out.sourceFile.data;res.json({success:true,template:out});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.delete("/templates/:id",async(req,res)=>{try{const t=await SmartFormTemplate.findOne({_id:req.params.id,tenantId:req.smartTenant._id});if(!t)return res.status(404).json({success:false,message:"Form not found"});const used=await SmartFormDocument.exists({tenantId:req.smartTenant._id,templateId:t._id});if(used){t.active=false;t.archived=true;await t.save();return res.json({success:true,archived:true,message:"Form archived because it has trip history"});}await t.deleteOne();res.json({success:true,deleted:true});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.delete("/organizations/:organizationId",async(req,res)=>{try{const organizationId=clean(req.params.organizationId);const used=await SmartFormDocument.exists({tenantId:req.smartTenant._id,organizationId});if(used){await SmartFormTemplate.updateMany({tenantId:req.smartTenant._id,organizationId},{$set:{active:false,archived:true}});return res.json({success:true,archived:true,message:"Organization archived because it has trip history"});}await SmartFormTemplate.deleteMany({tenantId:req.smartTenant._id,organizationId});res.json({success:true,deleted:true});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.post("/sheets",async(req,res)=>{try{const organizationId=clean(req.body.organizationId);const template=await SmartFormTemplate.findOne({_id:req.body.templateId,tenantId:req.smartTenant._id,organizationId,active:true,archived:{$ne:true}});if(!template)return res.status(404).json({success:false,message:"Active form not found"});const trips=Array.isArray(req.body.trips)?req.body.trips:[];if(!trips.length)return res.status(400).json({success:false,message:"Enter at least Trip 1"});const maxSlot=Math.max(1,...(template.fields||[]).map(slotFromField).filter(Boolean));if(trips.length>maxSlot)return res.status(400).json({success:false,message:`This form supports ${maxSlot} trip slot(s)`});const cleanTrips=[];for(let i=0;i<trips.length;i++){const x=trips[i]||{};const core=requiredTripValues(x);if(!core.pickup||!core.dropoff||!core.tripDate||!core.tripTime)return res.status(400).json({success:false,message:`Trip ${i+1}: Pickup, Drop-off, Date and Time are required`});if(!clean(x.serviceKey))return res.status(400).json({success:false,message:`Trip ${i+1}: Service is required`});const svc=await findEnabledService(req.smartTenant._id,x.serviceKey);if(!svc)return res.status(400).json({success:false,message:`Trip ${i+1}: selected service is not enabled`});cleanTrips.push({slot:i+1,clientName:clean(x.clientName),clientPhone:clean(x.clientPhone),memberId:clean(x.memberId),...core,serviceKey:upper(svc.serviceKey||svc.serviceCode||svc.serviceIdentity),serviceName:clean(svc.serviceName||svc.serviceTitle||svc.name||svc.title),values:x.values&&typeof x.values==="object"?x.values:{}});}const sheetSeq=await nextCounter(req.smartTenant._id,"sheet");const sheetNumber=`SFS${String(sheetSeq).padStart(4,"0")}`;const doc=await SmartFormDocument.create({tenantId:req.smartTenant._id,organizationId,organizationName:template.organizationName,templateId:template._id,templateVersion:template.version,sheetNumber,commonValues:req.body.commonValues&&typeof req.body.commonValues==="object"?req.body.commonValues:{},draftTrips:cleanTrips,status:"ENTRY_REVIEW"});res.status(201).json({success:true,document:doc});}catch(e){console.error("SMART FORM SHEET CREATE ERROR",e);res.status(500).json({success:false,message:e.message});}});
router.get("/review",async(req,res)=>{try{const organizationId=clean(req.query.organizationId);const q={tenantId:req.smartTenant._id,status:"ENTRY_REVIEW"};if(organizationId)q.organizationId=organizationId;const docs=await SmartFormDocument.find(q).sort({createdAt:1}).lean();res.json({success:true,documents:docs});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.put("/documents/:id/draft-trip/:slot",async(req,res)=>{try{const d=await SmartFormDocument.findOne({_id:req.params.id,tenantId:req.smartTenant._id,status:"ENTRY_REVIEW"});if(!d)return res.status(404).json({success:false,message:"Review sheet not found"});const row=d.draftTrips.find(x=>Number(x.slot)===Number(req.params.slot));if(!row)return res.status(404).json({success:false,message:"Trip row not found"});if(row.confirmed)return res.status(409).json({success:false,message:"Confirmed trip cannot be edited here"});for(const k of ["clientName","clientPhone","memberId","pickup","dropoff","tripDate","tripTime","serviceKey","serviceName"]){if(req.body[k]!==undefined)row[k]=req.body[k];}if(req.body.values&&typeof req.body.values==="object")row.values=req.body.values;await d.save();res.json({success:true,document:d});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.delete("/documents/:id/draft-trip/:slot",async(req,res)=>{try{const d=await SmartFormDocument.findOne({_id:req.params.id,tenantId:req.smartTenant._id,status:"ENTRY_REVIEW"});if(!d)return res.status(404).json({success:false,message:"Review sheet not found"});const row=d.draftTrips.find(x=>Number(x.slot)===Number(req.params.slot));if(row?.confirmed)return res.status(409).json({success:false,message:"Confirmed trip cannot be deleted"});d.draftTrips=d.draftTrips.filter(x=>Number(x.slot)!==Number(req.params.slot));if(!d.draftTrips.length){await d.deleteOne();return res.json({success:true,deletedSheet:true});}await d.save();res.json({success:true,document:d});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.post("/documents/:id/confirm",async(req,res)=>{const session=await mongoose.startSession();try{let result=null;await session.withTransaction(async()=>{const d=await SmartFormDocument.findOne({_id:req.params.id,tenantId:req.smartTenant._id,status:"ENTRY_REVIEW"}).session(session);if(!d)throw Object.assign(new Error("Review sheet not found"),{status:404});const template=await SmartFormTemplate.findOne({_id:d.templateId,tenantId:req.smartTenant._id,organizationId:d.organizationId}).session(session);if(!template)throw Object.assign(new Error("Form template not found"),{status:404});const created=[];for(const row of d.draftTrips){if(row.confirmed&&row.tripId)continue;const core=requiredTripValues(row);if(!core.pickup||!core.dropoff||!core.tripDate||!core.tripTime)throw new Error(`Trip ${row.slot}: Pickup, Drop-off, Date and Time are required`);const svc=await Service.findOne({tenantId:req.smartTenant._id,companyEnabled:true,$or:[{serviceKey:upper(row.serviceKey)},{serviceCode:upper(row.serviceKey)},{serviceIdentity:upper(row.serviceKey)}]}).session(session);if(!svc)throw new Error(`Trip ${row.slot}: Service is not enabled`);const seq=await nextCounter(req.smartTenant._id,"trip");const number=`SF${orgCode(template.organizationName)}${seq}${serviceCode(svc)}`;const tripPayload={tenantId:req.smartTenant._id,tenantSlug:req.smartTenant.slug||"",tripNumber:number,type:"smart-form",company:template.organizationType==="COMPANY"?template.organizationName:"",brokerName:template.organizationType==="BROKER"?template.organizationName:"",externalSource:"SMART_FORM",entryName:req.authUser.name||"Smart Forms",clientName:clean(row.clientName),clientPhone:clean(row.clientPhone),memberId:clean(row.memberId),pickup:core.pickup,dropoff:core.dropoff,tripDate:core.tripDate,tripTime:core.tripTime,status:"Scheduled",dispatchSelected:false,serviceKey:upper(svc.serviceKey||svc.serviceCode||svc.serviceIdentity),serviceCode:serviceCode(svc),serviceIdentity:upper(svc.serviceIdentity||svc.serviceKey),serviceName:clean(svc.serviceName||svc.serviceTitle||svc.name||svc.title),serviceTitle:clean(svc.serviceTitle||svc.serviceName||svc.name||svc.title),serviceSuffix:serviceCode(svc),tripNumberSuffix:serviceCode(svc),bookingData:{smartForm:{documentId:String(d._id),templateId:String(d.templateId),sheetNumber:d.sheetNumber,slot:Number(row.slot),organizationId:d.organizationId}}};const [trip]=await Trip.create([tripPayload],{session});row.confirmed=true;row.tripId=trip._id;row.tripNumber=number;d.tripIds.push(trip._id);d.slotAssignments.push({slot:Number(row.slot),tripId:trip._id,tripNumber:number});created.push({slot:row.slot,tripId:trip._id,tripNumber:number});}d.status="CONFIRMED";d.confirmedAt=new Date();await d.save({session});result={document:d,created};});res.json({success:true,...result});}catch(e){console.error("SMART FORM CONFIRM ERROR",e);res.status(e.status||500).json({success:false,message:e.message});}finally{await session.endSession();}});
router.get("/documents",async(req,res)=>{const q={tenantId:req.smartTenant._id};if(req.query.organizationId)q.organizationId=clean(req.query.organizationId);if(req.query.status)q.status=upper(req.query.status);const docs=await SmartFormDocument.find(q).select("-generatedFile.data").sort({updatedAt:-1}).lean();res.json({success:true,documents:docs});});
router.put("/documents/:id",async(req,res)=>{const d=await SmartFormDocument.findOne({_id:req.params.id,tenantId:req.smartTenant._id,organizationId:clean(req.body.organizationId)});if(!d)return res.status(404).json({success:false,message:"Document not found"});if(req.body.manualOverrides&&typeof req.body.manualOverrides==="object")d.manualOverrides=req.body.manualOverrides;const t=await SmartFormTemplate.findOne({_id:d.templateId,tenantId:req.smartTenant._id,organizationId:d.organizationId});if(t){try{d.generatedFile.data=await builder.buildPdf(t,d.values,d.manualOverrides);d.generatedFile.generatedAt=new Date();}catch(err){if(err.code!=="PDF_LIB_MISSING")throw err;}}await d.save();res.json({success:true,document:d});});
router.post("/documents/:id/finalize",async(req,res)=>{const d=await SmartFormDocument.findOne({_id:req.params.id,tenantId:req.smartTenant._id,organizationId:clean(req.body.organizationId)});if(!d)return res.status(404).json({success:false,message:"Document not found"});d.status="FINALIZED";d.finalizedAt=new Date();d.finalizedBy=req.authUser.name;await d.save();res.json({success:true,document:d});});
router.get("/documents/:id/file",async(req,res)=>{const d=await SmartFormDocument.findOne({_id:req.params.id,tenantId:req.smartTenant._id,organizationId:clean(req.query.organizationId)});if(!d?.generatedFile?.data)return res.status(404).json({success:false,message:"Generated PDF is not available yet"});res.type(d.generatedFile.mimeType||"application/pdf").send(d.generatedFile.data);});
module.exports=router;
