const express=require("express");
const jwt=require("jsonwebtoken");
const multer=require("multer");
const Tenant=require("../models/Tenant");
const Trip=require("../models/Trip");
const SmartFormTemplate=require("../models/SmartFormTemplate");
const SmartFormDocument=require("../models/SmartFormDocument");
const analyzer=require("../services/smartFormAnalyzerService");
const converter=require("../services/smartFormConverterService");
const generator=require("../services/smartFormGeneratorService");
const builder=require("../services/smartFormBuilderService");
const mapping=require("../services/smartFormMappingService");
const router=express.Router();const JWT_SECRET=process.env.JWT_SECRET||"dev_secret";
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024,files:1}});
function bearer(req){const h=String(req.headers.authorization||"").trim();return h.toLowerCase().startsWith("bearer ")?h.slice(7).trim():"";}
function auth(req,res,next){try{const v=jwt.verify(bearer(req),JWT_SECRET);req.authUser={id:v.id||null,name:v.name||v.username||"",role:v.role||"",tenantId:v.tenantId||null};if(req.authUser.role!=="PLATFORM_ADMIN"&&!req.authUser.tenantId)return res.status(403).json({success:false,message:"Tenant Required"});next();}catch(_){return res.status(401).json({success:false,message:"Invalid Token"});}}
function tenantId(req){return req.authUser.role==="PLATFORM_ADMIN"?String(req.query.tenantId||req.body?.tenantId||""):String(req.authUser.tenantId||"");}
async function gate(req,res,next){const id=tenantId(req);const t=await Tenant.findById(id);if(!t)return res.status(404).json({success:false,message:"Tenant not found"});if(t.smartFormsEnabled!==true)return res.status(403).json({success:false,message:"Smart Forms is disabled for this company"});req.smartTenant=t;next();}
router.use(auth);
router.get("/feature",async(req,res)=>{try{const t=await Tenant.findById(tenantId(req)).select("smartFormsEnabled").lean();res.json({success:true,enabled:t?.smartFormsEnabled===true});}catch(_){res.status(500).json({success:false,enabled:false});}});
router.use(gate);
router.get("/templates",async(req,res)=>{const q={tenantId:req.smartTenant._id};if(req.query.organizationId)q.organizationId=String(req.query.organizationId);const templates=await SmartFormTemplate.find(q).select("-sourceFile.data").sort({updatedAt:-1}).lean();res.json({success:true,templates});});
router.get("/templates/:id/source",async(req,res)=>{const t=await SmartFormTemplate.findOne({_id:req.params.id,tenantId:req.smartTenant._id});if(!t||!t.sourceFile?.data)return res.status(404).end();res.type(t.sourceFile.mimeType||"application/octet-stream").send(t.sourceFile.data);});
router.get("/templates/:id/editable",async(req,res)=>{try{const q={_id:req.params.id,tenantId:req.smartTenant._id};if(req.query.organizationId)q.organizationId=String(req.query.organizationId);const t=await SmartFormTemplate.findOne(q);if(!t||!t.sourceFile?.data)return res.status(404).json({success:false,message:"Template source not found"});const made=await converter.buildEditablePdfFromTemplate(t);res.set("Cache-Control","no-store");res.set("X-Smart-Form-Fields",String(made.created));res.type("application/pdf").send(made.buffer);}catch(err){console.error("SMART FORM EDITABLE ERROR",err);res.status(err.code==="SMART_FORM_UNSUPPORTED_SOURCE"?415:500).json({success:false,message:err.message});}});
router.post("/templates/analyze",upload.single("file"),async(req,res)=>{try{if(!req.file)return res.status(400).json({success:false,message:"Blank form file is required"});const organizationId=String(req.body.organizationId||"").trim();const organizationName=String(req.body.organizationName||"").trim();if(!organizationId||!organizationName)return res.status(400).json({success:false,message:"Organization is required"});const analysis=await analyzer.analyzeBlankForm(req.file);const mapped=mapping.applyAutoMappings(analysis.fields);await converter.buildEditablePdf(req.file,mapped);const doc=await SmartFormTemplate.create({tenantId:req.smartTenant._id,organizationId,organizationName,organizationType:String(req.body.organizationType||"INSURANCE").toUpperCase(),name:String(req.body.name||organizationName).trim(),sourceFile:{originalName:req.file.originalname,mimeType:req.file.mimetype,size:req.file.size,data:req.file.buffer},pageCount:analysis.pageCount,sections:analysis.sections,fields:mapped,analysisProvider:analysis.analysisProvider,analyzedAt:new Date(),createdBy:req.authUser.name,updatedBy:req.authUser.name});const out=doc.toObject();delete out.sourceFile.data;res.status(201).json({success:true,template:out,editableReady:true});}catch(err){console.error("SMART FORM ANALYZE ERROR",err);res.status(err?.code===11000?409:err?.code==="SMART_FORM_UNSUPPORTED_SOURCE"?415:500).json({success:false,message:err?.code===11000?"A form template already exists with this name for this organization":err.message});}});
router.put("/templates/:id",async(req,res)=>{try{const t=await SmartFormTemplate.findOne({_id:req.params.id,tenantId:req.smartTenant._id,organizationId:String(req.body.organizationId||req.query.organizationId||"")});if(!t)return res.status(404).json({success:false,message:"Template not found"});for(const k of ["name","organizationName","organizationType","active"]){if(req.body[k]!==undefined)t[k]=req.body[k];}if(Array.isArray(req.body.fields))t.fields=req.body.fields;if(Array.isArray(req.body.sections))t.sections=req.body.sections;t.updatedBy=req.authUser.name;await t.save();const out=t.toObject();delete out.sourceFile.data;res.json({success:true,template:out});}catch(err){res.status(500).json({success:false,message:err.message});}});
router.get("/completed-trips",async(req,res)=>{const organizationId=String(req.query.organizationId||"").trim();const template=await SmartFormTemplate.findOne({tenantId:req.smartTenant._id,organizationId,active:true}).lean();if(!template)return res.json({success:true,trips:[]});const q={tenantId:req.smartTenant._id,status:/^completed$/i};if(template.organizationType==="BROKER")q.brokerName=template.organizationName;else if(template.organizationType==="COMPANY")q.company=template.organizationName;const trips=await Trip.find(q).sort({tripDate:-1,tripTime:-1}).limit(250).lean();res.json({success:true,trips});});
router.post("/documents/generate",async(req,res)=>{try{const organizationId=String(req.body.organizationId||"");const template=await SmartFormTemplate.findOne({_id:req.body.templateId,tenantId:req.smartTenant._id,organizationId});if(!template)return res.status(404).json({success:false,message:"Template not found"});const ids=Array.isArray(req.body.tripIds)?req.body.tripIds:[];const trips=await Trip.find({_id:{$in:ids},tenantId:req.smartTenant._id,status:/^completed$/i}).sort({tripDate:1,tripTime:1});if(trips.length!==ids.length)return res.status(422).json({success:false,message:"Every selected trip must exist in this tenant and be Completed"});const doc=await generator.generate({tenant:req.smartTenant,template,trips,userName:req.authUser.name});res.status(201).json({success:true,document:{...doc.toObject(),generatedFile:{mimeType:doc.generatedFile.mimeType,generatedAt:doc.generatedFile.generatedAt,available:!!doc.generatedFile.data}}});}catch(err){console.error("SMART FORM GENERATE ERROR",err);res.status(500).json({success:false,message:err.message});}});
router.get("/documents",async(req,res)=>{const q={tenantId:req.smartTenant._id};if(req.query.organizationId)q.organizationId=String(req.query.organizationId);if(req.query.status)q.status=String(req.query.status).toUpperCase();const docs=await SmartFormDocument.find(q).select("-generatedFile.data").sort({updatedAt:-1}).lean();res.json({success:true,documents:docs});});
router.put("/documents/:id",async(req,res)=>{const d=await SmartFormDocument.findOne({_id:req.params.id,tenantId:req.smartTenant._id,organizationId:String(req.body.organizationId||"")});if(!d)return res.status(404).json({success:false,message:"Document not found"});if(req.body.manualOverrides&&typeof req.body.manualOverrides==="object")d.manualOverrides=req.body.manualOverrides;const t=await SmartFormTemplate.findOne({_id:d.templateId,tenantId:req.smartTenant._id,organizationId:d.organizationId});if(t){try{d.generatedFile.data=await builder.buildPdf(t,d.values,d.manualOverrides);d.generatedFile.generatedAt=new Date();}catch(err){if(err.code!=="PDF_LIB_MISSING")throw err;}}await d.save();res.json({success:true,document:d});});
router.post("/documents/:id/finalize",async(req,res)=>{const d=await SmartFormDocument.findOne({_id:req.params.id,tenantId:req.smartTenant._id,organizationId:String(req.body.organizationId||"")});if(!d)return res.status(404).json({success:false,message:"Document not found"});d.status="FINALIZED";d.finalizedAt=new Date();d.finalizedBy=req.authUser.name;await d.save();res.json({success:true,document:d});});
router.get("/documents/:id/file",async(req,res)=>{const d=await SmartFormDocument.findOne({_id:req.params.id,tenantId:req.smartTenant._id,organizationId:String(req.query.organizationId||"")});if(!d?.generatedFile?.data)return res.status(404).json({success:false,message:"Generated PDF is not available. Install pdf-lib on the server if generation is pending."});res.type(d.generatedFile.mimeType||"application/pdf").send(d.generatedFile.data);});
module.exports=router;
